// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResultMsg struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultMsg) Reset()         { *m = ResultMsg{} }
func (m *ResultMsg) String() string { return proto.CompactTextString(m) }
func (*ResultMsg) ProtoMessage()    {}
func (*ResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *ResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultMsg.Unmarshal(m, b)
}
func (m *ResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultMsg.Marshal(b, m, deterministic)
}
func (m *ResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultMsg.Merge(m, src)
}
func (m *ResultMsg) XXX_Size() int {
	return xxx_messageInfo_ResultMsg.Size(m)
}
func (m *ResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResultMsg proto.InternalMessageInfo

func (m *ResultMsg) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type Parameters struct {
	Para1                int32    `protobuf:"varint,1,opt,name=para1,proto3" json:"para1,omitempty"`
	Para2                int32    `protobuf:"varint,2,opt,name=para2,proto3" json:"para2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameters) Reset()         { *m = Parameters{} }
func (m *Parameters) String() string { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()    {}
func (*Parameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *Parameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameters.Unmarshal(m, b)
}
func (m *Parameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameters.Marshal(b, m, deterministic)
}
func (m *Parameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameters.Merge(m, src)
}
func (m *Parameters) XXX_Size() int {
	return xxx_messageInfo_Parameters.Size(m)
}
func (m *Parameters) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameters.DiscardUnknown(m)
}

var xxx_messageInfo_Parameters proto.InternalMessageInfo

func (m *Parameters) GetPara1() int32 {
	if m != nil {
		return m.Para1
	}
	return 0
}

func (m *Parameters) GetPara2() int32 {
	if m != nil {
		return m.Para2
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ResultMsg)(nil), "helloworld.ResultMsg")
	proto.RegisterType((*Parameters)(nil), "helloworld.Parameters")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xb7, 0xe2, 0xee, 0xba, 0xa3, 0x20, 0x0c, 0xba, 0x94, 0xf5, 0x22, 0x11, 0xc4, 0x53,
	0xd0, 0x7a, 0xf1, 0x20, 0x82, 0x7b, 0xd1, 0x8b, 0x50, 0xe2, 0xc1, 0x73, 0xb4, 0x43, 0x15, 0x12,
	0x13, 0x93, 0x14, 0xed, 0x13, 0xf8, 0xda, 0x92, 0xd8, 0xda, 0x0a, 0x7b, 0x9b, 0x6f, 0xfa, 0x95,
	0xfc, 0xff, 0xc0, 0xee, 0x2b, 0x29, 0x65, 0xb8, 0x75, 0x26, 0x18, 0x84, 0x04, 0x9f, 0xc6, 0xa9,
	0x8a, 0x31, 0xd8, 0xbb, 0x8f, 0x24, 0xe8, 0xa3, 0x21, 0x1f, 0x10, 0x61, 0xfb, 0x5d, 0x6a, 0xca,
	0xb3, 0xe3, 0xec, 0x6c, 0x21, 0xd2, 0xcc, 0x4e, 0x01, 0x3a, 0xc7, 0xaa, 0x16, 0x73, 0x98, 0x6b,
	0xf2, 0x5e, 0xd6, 0xbd, 0xd4, 0x23, 0x3b, 0x81, 0x85, 0x20, 0xdf, 0xa8, 0xf0, 0xe0, 0x6b, 0x5c,
	0xc2, 0xcc, 0x25, 0x48, 0xd6, 0x54, 0x74, 0xc4, 0xae, 0x00, 0x4a, 0xe9, 0xa4, 0xa6, 0x40, 0xce,
	0xe3, 0x01, 0x4c, 0xad, 0x74, 0xf2, 0xa2, 0x93, 0x7e, 0xa1, 0xdf, 0x16, 0xf9, 0xd6, 0xb0, 0x2d,
	0x8a, 0xef, 0x0c, 0xe6, 0x77, 0x8e, 0xe2, 0x8f, 0x78, 0x03, 0x3b, 0x8f, 0xb2, 0x4d, 0xa9, 0x30,
	0xe7, 0x43, 0x1f, 0x3e, 0x2e, 0xb3, 0x5a, 0x6e, 0xf8, 0x62, 0x55, 0xcb, 0x26, 0x78, 0x1d, 0xa3,
	0x6a, 0x13, 0xe8, 0xb6, 0xaa, 0xf0, 0x9f, 0x36, 0x84, 0x5b, 0x1d, 0x8e, 0xf7, 0x7f, 0xcd, 0xd8,
	0x64, 0x7d, 0x0e, 0x47, 0x6f, 0x86, 0xd7, 0xce, 0xbe, 0x70, 0xfa, 0x92, 0xda, 0x2a, 0xf2, 0x23,
	0x75, 0xbd, 0x9f, 0x9e, 0x7a, 0x8a, 0x73, 0x19, 0x0f, 0x5e, 0x66, 0xcf, 0xb3, 0x74, 0xf9, 0xcb,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x89, 0x81, 0x82, 0x88, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	RemoteAdd(ctx context.Context, in *Parameters, opts ...grpc.CallOption) (*ResultMsg, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) RemoteAdd(ctx context.Context, in *Parameters, opts ...grpc.CallOption) (*ResultMsg, error) {
	out := new(ResultMsg)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/RemoteAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	RemoteAdd(context.Context, *Parameters) (*ResultMsg, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_RemoteAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RemoteAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/RemoteAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RemoteAdd(ctx, req.(*Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "RemoteAdd",
			Handler:    _Greeter_RemoteAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
